services:
  - type: web
    name: skillpath-graph
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: COGNODB_URI
        sync: false
      - key: COGNODB_USERNAME
        value: cognodb
      - key: COGNODB_PASSWORD
        sync: false
